name: Build HTML from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate HTML from Markdown
        run: |
          pandoc --css=styling.css -V lang=en -V highlighting-css= --mathjax -s -f markdown+smart --metadata --to=html5 index.md -o index.html

      - name: Commit and push generated HTML
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add index.html
          git commit -m "Update generated index.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
